//
// DeviceEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class DeviceEntity: JSONEncodable {

    public enum Status: String { 
        case using = "using"
        case free = "free"
    }
    public var userName: String?
    public var mailAddress: String?
    public var deviceName: String?
    public var deviceId: String?
    public var returnDate: ISOFullDate?
    public var status: Status?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["userName"] = self.userName
        nillableDictionary["mailAddress"] = self.mailAddress
        nillableDictionary["deviceName"] = self.deviceName
        nillableDictionary["deviceId"] = self.deviceId
        nillableDictionary["returnDate"] = self.returnDate?.encodeToJSON()
        nillableDictionary["status"] = self.status?.rawValue

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

