//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire
import RxSwift



open class DefaultAPI: APIBase {
    /**
     getList
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getList(completion: @escaping ((_ data: [DeviceEntity]?,_ error: Error?) -> Void)) {
        getListWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     getList
     
     - returns: Observable<[DeviceEntity]>
     */
    open class func getList() -> Observable<[DeviceEntity]> {
        return Observable.create { observer -> Disposable in
            getList() { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return NopDisposable.instance
        }
    }

    /**
     getList
     - GET /exec
     - examples: [{contentType=application/json, example=[ {
  "returnDate" : "2000-01-23T04:56:07.000+00:00",
  "mailAddress" : "aeiou",
  "userName" : "aeiou",
  "deviceName" : "aeiou",
  "deviceId" : "aeiou",
  "status" : "aeiou"
} ]}]

     - returns: RequestBuilder<[DeviceEntity]> 
     */
    open class func getListWithRequestBuilder() -> RequestBuilder<[DeviceEntity]> {
        let path = "/exec"
        let URLString = DeviceKanriSanAPIAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[DeviceEntity]>.Type = DeviceKanriSanAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     update
     
     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func update(body: DeviceEntity, completion: @escaping ((_ data: MessageEntity?,_ error: Error?) -> Void)) {
        updateWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     update
     
     - parameter body: (body)  
     - returns: Observable<MessageEntity>
     */
    open class func update(body: DeviceEntity) -> Observable<MessageEntity> {
        return Observable.create { observer -> Disposable in
            update(body: body) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return NopDisposable.instance
        }
    }

    /**
     update
     - POST /exec
     - update
     - examples: [{contentType=application/json, example={
  "message" : "aeiou"
}}]
     
     - parameter body: (body)  

     - returns: RequestBuilder<MessageEntity> 
     */
    open class func updateWithRequestBuilder(body: DeviceEntity) -> RequestBuilder<MessageEntity> {
        let path = "/exec"
        let URLString = DeviceKanriSanAPIAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<MessageEntity>.Type = DeviceKanriSanAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
